server:
  port: 8087
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/car_shopping"
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true